### ISSUE TITLE
graphql-ws subscription behaviour is not compatible with AWS api. 

### ISSUE THREAD

**Issue by ret-smart** [enisdenjo/graphql-ws#602] opened 2024-12-03 11:35 UTC
**Screenshot**
i set a console.log at validateMessage:

```
"id": "5c87a716-0053-4755-b949-ef2cdf1d038c",
  "type": "subscribe",
  "payload": {
    "query": "subscription OnUpdateDatapoint {\n        onUpdateDatapoint {\n            id\n            value\n        }\n    }",
    "variables": {},
    "extensions": {
      "authorization": {
        "host": "XXXX.appsync-api.eu-west-1.amazonaws.com",
        "authorization": "Bearer Token"
      }
    }
  }
}
message= {
  "type": "ka"
}
message= {
  "type": "error",
  "payload": {
    "errors": [
      {
        "errorType": "UnsupportedOperation",
        "message": "unknown not supported through the realtime channel"
      }
    ]
  }
}

```
Error: Error: "error" message expects the 'id' property to be a string, but got undefined

**Expected Behaviour**
[https://docs.aws.amazon.com/en_us/appsync/latest/devguide/real-time-websocket-client.html]
i checked the websocket environment with this specification and it has worked with wscat.

the ka message leads to an error.

**Actual Behaviour**
I checked the source code the i saw tht the component uses other requests than AWS does.

**Debug Information**
create an AWS amplify api and check subscription.

**Further Information**
I can send my source code, if requested.

**Comment by enisdenjo** [comment] 2024-12-18 09:12
Duplicate of #241.

**Closed by enisdenjo** 2024-12-18 09:12 UTC
