### ISSUE TITLE
Errors Initiating connection to subscription service

### ISSUE THREAD

**Issue by Efosaok** [enisdenjo/graphql-ws#235] opened 2021-09-16 03:03 UTC
**Screenshot**
Visualising is always helpful.

**Expected Behaviour**
I expected it to do _this_ -

**Actual Behaviour**
but instead it did _this_.

**Debug Information**
Help us debug the bug?

**Further Information**
Anything else you might find helpful.

**Comment by enisdenjo** [comment] 2021-09-16 08:09
Duplicate of #236.

**Closed by enisdenjo** 2021-09-16 08:09 UTC
