### ISSUE TITLE
Using split() from Apollo Client with wsLink doesn't connect

### ISSUE THREAD

**Issue by helderjbe** [enisdenjo/graphql-ws#156] opened 2021-04-15 14:13 UTC
Following the README in the section "Client usage with Apollo", the connection works as expected, but when splitting the link like so:

```
const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  uploadLink,
);

export const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  // eslint-disable-next-line unicorn/prefer-spread
  link: authLink.concat(errorLink).concat(splitLink),
});
```

It doesn't connect anymore (no error messages, and checking from network tab it's a clear non-connection issue). Is there a way that I'm missing here?

-------------------------------
wsLink:
```
const wsLink = new WebSocketLink({
  url: GQL_URL?.replace('http://', 'ws://').replace('https://', 'wss://') || '',
  connectionParams: () => {
    const token = localStorage.getItem('authToken');
    if (!token) {
      return {};
    }
    return {
      Authorization: `Bearer ${token}`,
    };
  },
});
```

WebSocketLink:
```
class WebSocketLink extends ApolloLink {
  private client: Client;

  constructor(options: ClientOptions) {
    super();
    this.client = createClient(options);
  }

  public request(operation: Operation): Observable<FetchResult> {
    return new Observable((sink) => {
      return this.client.subscribe<FetchResult>(
        { ...operation, query: print(operation.query) },
        {
          next: sink.next.bind(sink),
          complete: sink.complete.bind(sink),
          error: (err) => {
            if (err instanceof Error) {
              return sink.error(err);
            }

            if (err instanceof CloseEvent) {
              return sink.error(
                // reason will be available on clean closes
                new Error(
                  `Socket closed with event ${err.code} ${err.reason || ''}`,
                ),
              );
            }

            return sink.error(
              new Error(
                (err as GraphQLError[])
                  .map(({ message }) => message)
                  .join(', '),
              ),
            );
          },
        },
      );
    });
  }
}
```

**Comment by enisdenjo** [comment] 2021-04-15 14:25
Hey there, this seems to be a duplicate of https://github.com/enisdenjo/graphql-ws/issues/130. I'd bet it is an issue with Apollo.

**Comment by enisdenjo** [comment] 2021-04-15 14:50
Just a small FYI, I have absolutely zero experience with Apollo 😅. So, if there is no explicit link to `graphql-ws` failing, I cannot be of much help.

However, if you provide me with a repro, I would be happy to dig around a little.

**Comment by enisdenjo** [comment] 2021-04-19 18:03
@helderjbe any news?

**Comment by enisdenjo** [comment] 2021-04-25 13:52
Closing due to inactivity. @helderjbe feel free to reopen the issue if you find proof that `graphql-ws` is causing it.

**Closed** 2021-04-25 13:53 UTC
Labels: question

**Comment by ntziolis** [comment] 2021-04-30 06:27
For anyone finding this. We are able to use apollo split link + `graphql-ws` together successfully (no difference to using the old ws lib, it was a drop in replacement for us). So if you are running into issues its likely connected to incorrect configuration.
